sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSbj87AdLedWQBPUz9N
    access-key-secret: rqfkZokGtFkyevtTGdpKPwMLjyDOJE
    bucket-name: max-sky-take-out
